server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/salesdb
spring.datasource.username=postgres
spring.datasource.password=yeison

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.drop-first=false
